Update Prod workflow

diff --git a/.github/workflows/prod.yml b/.github/workflows/prod.yml
--- a/.github/workflows/prod.yml
+++ b/.github/workflows/prod.yml
@@ -1,14 +1,13 @@
 name: Production
 
 on:
-  push:
-    branches:
-      - prod
-      - main
+push:
+branches:
+- prod
 
 jobs:
-  deploy:
-    runs-on: ubuntu-latest
+deploy:
+runs-on: ubuntu-latest
 
     steps:
       - name: Checkout code
@@ -22,37 +21,37 @@ jobs:
           key: ${{ secrets.SSH_PRIVATE_KEY }} 
 
           script: |
-            # Menambahkan 'set -e' agar skrip berhenti jika ada perintah yang gagal
+            # Add 'set -e' to stop the script if any command fails.
             set -e
 
-            # 1. Pindah ke direktori proyek
+            # 1. Move to project directory
             echo "Changing directory..."
             cd /home/laravel-boilerplate/htdocs/laravel-boilerplate.vngne.tech/laravel-boilerplate
 
-            # 2. Masuk ke mode maintenance agar user tidak mengalami error saat proses deploy
+            # 2. Maintenance Mode
             echo "Activating maintenance mode..."
             php artisan down
 
-            # 3. Tarik perubahan terbaru dari branch 'prod'
+            # 3. Pull
             echo "Pulling latest code from prod branch..."
             git pull origin main
 
-            # 4. Install dependensi Composer (hanya jika ada perubahan di composer.lock)
+            # 4. Install Dependencies
             echo "Installing Composer dependencies..."
             composer install --no-interaction --prefer-dist --optimize-autoloader
 
-            # 5. Jalankan migrasi database
+            # 5. Run Database Migrations
             echo "Running database migrations..."
             php artisan migrate --force
 
-            # 6. Bersihkan dan buat cache baru untuk performa
+            # 6. Clear Cache
             echo "Clearing cache and creating new cache..."
             php artisan optimize:clear
             php artisan config:cache
             php artisan route:cache
             php artisan view:cache
 
-            # 7. Keluar dari mode maintenance
+            # 7. Exit maintenance mode
             echo "Deactivating maintenance mode..."
             php artisan up
 
